### ISSUE TITLE
Windows Port

### ISSUE THREAD

**Issue by Demonslay335** [pekeinfo/DecryptCrypren#1]
Excellent job in reversing this ransomware and providing a solution!

I am currently working on a Windows port with a GUI for the average user. I have it nearly finished, just cleaning things up. I also added the ability to pull the key from a DOCX file, plan to add more formats that have such blank sections of 0 bytes that would allow for the key to be easily visible.

Am I correct in assuming that the key can also be derived by comparing a before and after file? Simply something like `keyBytes[i] = encryptedBytes[i] - cleanBytes[i]`? This would theoretically allow key retrieval from any file type if it holds true.

**Comment by pekeinfo** [comment]
yes but it's necessary the file have a block with zero of the length 64 or more.
The cypher used is in block of the 64.
It very important what first byte key are correct.
